Gemfile
Gemfile.lock

kaminariのバージョンは1.1.1 (カリキュラム通り)
bootstrapのバージョンは最新の3.6.1にしました。
(柏木さんに聞いたところ)gemのバージョンはrailsのバージョンとデプロイする際のAWSのバージョンによるらしいのですが、ひとまず最新バージョンで大丈夫そうです。kaminariは不安なのでカリキュラム通りにしました。

:sparkles: gemをすべて追加しました。

---

app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
config/initializers/devise.rb
config/routes.rb
db/migrate/20190827012435_devise_create_users.rb
db/migrate/20190827012947_add_column_to_users.rb
db/schema.rb
test/fixtures/users.yml
test/models/user_test.rb

:sparkles: devise,userテーブルの追加

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/controllers/application_controller.rb
app/views/users/registrations/new.html.erb
app/views/users/sessions/new.html.erb
app/views/users/shared/_links.html.erb
config/routes.rb
db/migrate/20190827080706_add_column_to_users.rb
db/migrate/20190827081136_rename_postalcode_column_to_users.rb
db/schema.rb

:sparkles: ログイン機能の追加

---

app/controllers/admins/registrations_controller.rb
app/controllers/admins/sessions_controller.rb
app/controllers/application_controller.rb
app/controllers/users/registrations_controller.rb
app/controllers/users/sessions_controller.rb
app/views/users/registrations/new.html.erb

:sparkles: Admin用ログイン機能追加

---

config/routes.rb

GET | /admin/orders |  index | 注文の一覧画面の表示
GET | /admin/orders/:id | show | 注文の詳細画面の表示
PATCH | /admin/orders/:id | update | 注文の配送ステータスの変更
を追加しました。

:sparkles: orderに関するrootingを追加

---

app/controllers/end_user/items_controller.rb
app/views/admin/items/index.html.erb
app/views/admin/items/show.html.erb
app/views/end_user/items/index.html.erb
app/views/end_user/items/show.html.erb
app/views/layouts/_items.html.erb

商品詳細画面を作成しました。
とりあえず商品が持ってるカラムを表示しているだけです。

:sparkles: エンドユーザー商品詳細機能追加

---

app/assets/javascripts/application.js
app/controllers/admin/items_controller.rb
app/models/cd.rb
app/models/item.rb
app/models/song.rb
app/views/admin/items/_cd_fields.html.erb
app/views/admin/items/_form.html.erb
app/views/admin/items/_song_fields.html.erb
app/views/admin/items/show.html.erb
app/views/end_user/items/index.html.erb
app/views/end_user/items/show.html.erb
config/routes.rb
db/migrate/20190829062815_create_cds.rb
db/migrate/20190829065627_create_songs.rb
db/schema.rb
test/fixtures/cds.yml
test/fixtures/songs.yml
test/models/cd_test.rb
test/models/song_test.rb

商品追加フォームにCDと曲を同時に追加するフォームを作成しました。

:sparkles: CD, 曲の追加機能作成

---

app/models/cd.rb
app/models/song.rb
app/models/user.rb

:recycle: validationの設定

---

app/views/admin/items/index.html.erb
app/views/layouts/_items.html.erb
config/routes.rb

rootをログイン状態によって変更する
商品一覧の商品名から商品詳細へのリンクを作成

:sparkles: rootの設定, 商品のリンク先設定

---

app/assets/javascripts/end_user/reviews.coffee
app/assets/stylesheets/end_user/reviews.scss
app/controllers/end_user/items_controller.rb
app/controllers/end_user/reviews_controller.rb
app/helpers/end_user/reviews_helper.rb
app/models/item.rb
app/models/review.rb
app/models/user.rb
app/views/end_user/favorites/_favorite.html.erb
app/views/end_user/items/show.html.erb
app/views/reviews/_review.html.erb
db/migrate/20190831033745_create_reviews.rb
db/schema.rb
test/controllers/end_user/reviews_controller_test.rb
test/fixtures/reviews.yml
test/models/review_test.rb

:sparkles: レビュー機能の追加

---

app/controllers/admin/items_controller.rb

:bug: adminのitemsコントローラーの修復

---

app/assets/javascripts/end_user/carts.coffee
app/assets/stylesheets/end_user/carts.scss
app/controllers/application_controller.rb
app/controllers/end_user/carts_controller.rb
app/helpers/end_user/carts_helper.rb
app/models/cart.rb
app/models/item.rb
app/models/user.rb
app/views/end_user/carts/show.html.erb
app/views/end_user/items/show.html.erb
app/views/reviews/_review.html.erb
config/routes.rb
db/migrate/20190901004222_create_carts.rb
db/schema.rb
test/controllers/end_user/carts_controller_test.rb
test/fixtures/carts.yml
test/models/cart_test.rb

カート機能追加しました。
カートのルートで指定しているメソッドが間違っていたので修正しました。

:sparkles: カート機能の追加

---

app/controllers/end_user/carts_controller.rb
app/views/admin/items/index.html.erb
app/views/end_user/items/index.html.erb
app/views/layouts/_header.html.erb
config/routes.rb

:bug: カート遷移のルート修正

---

app/assets/stylesheets/application.scss
app/views/layouts/_header.html.erb

:bug: 名前が表示されないbugを修正

---

app/assets/javascripts/end_user/contacts.coffee
app/assets/stylesheets/end_user/contacts.scss
app/controllers/end_user/contacts_controller.rb
app/helpers/end_user/contacts_helper.rb
app/models/contact.rb
app/views/end_user/contacts/new.html.erb
config/routes.rb
db/migrate/20190904103009_create_contacts.rb
db/schema.rb
test/controllers/end_user/contacts_controller_test.rb
test/fixtures/contacts.yml
test/models/contact_test.rb

:sparkles: お問い合わせフォームを作成

---

app/assets/stylesheets/application.scss
app/views/layouts/_header.html.erb

・headerのguest状態の「会員登録」を「ログイン」に変更
・footerの位置を変更

:bug: footerの位置とheaderの表示を変更

---

app/controllers/admin/items_controller.rb
app/controllers/end_user/items_controller.rb
app/views/admin/items/index.html.erb
app/views/end_user/items/_favorite_ranking.html.erb
app/views/end_user/items/index.html.erb

:sparkles: いいねランキング機能の追加

---

Gemfile
Gemfile.lock
app/controllers/end_user/items_controller.rb
app/views/end_user/items/_item_search.html.erb
app/views/end_user/items/index.html.erb
app/views/layouts/application.html.erb

:sparkles: 商品検索機能の追加

---

app/assets/stylesheets/application.scss
app/views/layouts/_header.html.erb
app/views/layouts/application.html.erb

:bug: 改善しました！

---

app/views/layouts/_header.html.erb

:bug: 新規商品追加のpathを修正しました。

---

app/controllers/admin/items_controller.rb
app/views/admin/items/new.html.erb
config/routes.rb

:sparkles: アーティスト・レーベル・ジャンルの登録フォームの作成

---

app/controllers/admin/items_controller.rb

:bug: admin商品検索の修正

---

app/assets/stylesheets/application.scss
app/views/layouts/_footer.html.erb

:bug: footer下部に固定

---

app/assets/stylesheets/admin/contacts.scss
app/assets/stylesheets/end_user/contacts.scss
app/views/admin/contacts/index.html.erb
app/views/admin/contacts/show.html.erb
app/views/end_user/contacts/new.html.erb

:art: お問い合わせ部分のデザインを(軽く)調整

---

app/controllers/admin/items_controller.rb
app/models/cd.rb
app/models/song.rb
app/views/admin/items/new.html.erb

:bug: 複数商品追加できない修正

---

app/controllers/end_user/items_controller.rb

:bug: 検索機能のバグ修正

---

app/assets/stylesheets/application.scss
app/controllers/end_user/carts_controller.rb
app/controllers/end_user/payments_controller.rb
app/controllers/end_user/users_controller.rb
app/views/end_user/contacts/new.html.erb
app/views/end_user/users/show.html.erb
app/views/end_user/users/unsubscribe.html.erb
app/views/layouts/application.html.erb
config/application.rb
config/locales/devise.ja.yml
config/locales/ja.yml

・マイページの正しくない入力をおこなった時に出てくるエラーの修正
・サクセスメッセージの追加

:sparkles: サクセスメッセージの追加

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/end_user/items.scss
app/controllers/admins/registrations_controller.rb
app/controllers/admins/sessions_controller.rb
app/controllers/end_user/items_controller.rb
app/views/admin/items/index.html.erb
app/views/end_user/carts/show.html.erb
app/views/end_user/items/index.html.erb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
config/initializers/kaminari_config.rb
config/locales/ja.yml
config/routes.rb

:sparkles: pagenationの追加

---

Gemfile
Gemfile.lock
app/assets/javascripts/admin/users.coffee
app/assets/javascripts/application.js
app/assets/javascripts/end_user/payments.coffee
app/assets/javascripts/end_user/users.coffee
app/assets/javascripts/jquery.jpostal.js
app/controllers/end_user/contacts_controller.rb
app/models/contact.rb
app/views/admin/contacts/index.html.erb
app/views/admin/users/index.html.erb
app/views/admin/users/show.html.erb
app/views/end_user/_new_shipping_form.html.erb
app/views/end_user/carts/show.html.erb
app/views/end_user/payments/complete.html.erb
app/views/end_user/users/show.html.erb
app/views/layouts/_header.html.erb
app/views/layouts/application.html.erb
app/views/users/registrations/new.html.erb
app/views/users/shared/_links.html.erb

:sparkles: 郵便番号による住所の自動入力実装

---

app/assets/stylesheets/end_user/users.scss
app/views/end_user/carts/show.html.erb
app/views/end_user/payments/new.html.erb
app/views/layouts/application.html.erb
app/views/template/_favorite_index.html.erb
app/views/template/_order_history.html.erb

:art: マイページのデザイン変更

---

app/controllers/end_user/carts_controller.rb
app/views/end_user/carts/show.html.erb
config/routes.rb

:sparkles: カート一覧で個数変更機能実装

---

app/views/layouts/application.html.erb

:bug: jsni

---

app/assets/stylesheets/admin/contacts.scss
app/assets/stylesheets/end_user/carts.scss
app/assets/stylesheets/end_user/payments.scss
app/controllers/end_user/payments_controller.rb
app/views/end_user/carts/show.html.erb
app/views/end_user/contacts/new.html.erb
app/views/end_user/payments/confirm.html.erb
app/views/end_user/payments/new.html.erb
config/routes.rb

:bug: 購入確認画面の修正

---

app/controllers/end_user/payments_controller.rb

:bug: 購入して在庫が減るように修正
